### ISSUE TITLE
dont mix tree.get and [...] accessor pattern

### ISSUE THREAD

**Issue by marscher** [BAMWelDX/IIW2021_AA_CXII#1]
At the beginning of the notebook the get pattern is used, while later the brackets notation is used. Do you want to demonstrate that both things are possible?
In my opinion one should stick to one pattern (preferably the bracket notation).

**Comment by CagtayFabry** [comment]
The idea of the notebook is to run with every file that complies with the `datamodels/single_pass_weld-1.0.0.schema`
Since `reference_timestamp` and `wx_user` are optional properties the get pattern is used in these places to avoid running into errors.
